/*
 * Code to generate list of words having spelling mistakes. The words are 
 * generated by making random modifications to the list of words in dictionary
 * at /usr/share/dict/words.
 * The code uses random number generator to generate a random index within the 
 * input word for making changes.
 */

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
/**
 *
 * @author isingh
 */
public class BadWordGenerator {
  static char[] vowels = {'a', 'e', 'i', 'o', 'u'};
  /*
   * Function to change case of random character in the word.
   */
  public static String changeCase(String word) {
    StringBuilder sb = new StringBuilder(word);
    Random rand = new Random();
    int indexToChange = rand.nextInt(word.length());
    if (sb.charAt(indexToChange)>'a' && sb.charAt(indexToChange)<'z'){
           char c = Character.toUpperCase(sb.charAt(indexToChange));
           sb.setCharAt(indexToChange, c);           
    }
    else{
        char c = Character.toLowerCase(sb.charAt(indexToChange));
        sb.setCharAt(indexToChange, c);
    }
    return sb.toString();
  
  }
  /*
   * Function to change vowels in the word to random vowels.
   */
  public static String changeVowels(String word) {
    StringBuilder sb = new StringBuilder(word);
    Random rand = new Random();
    int vowelIndex = rand.nextInt(vowels.length);
    for(int i = 0; i < sb.length(); i++) {
      char c = sb.charAt(i);
      if((c == 'a') || (c == 'e') || (c == 'i') || (c == 'o') || (c == 'u')) {
          sb.setCharAt(i, vowels[vowelIndex]);
      }
    }
    return sb.toString();
  }
  
  /*
   * Function to add repetitive letter at random location in the word.
   */
  public static String repeatLetters(String word) {
    StringBuilder sb = new StringBuilder(word);
    Random rand = new Random();
    int indexToRepeat = rand.nextInt(sb.length());
    int repCount = rand.nextInt(sb.length());
    while (repCount > 0){
        sb.insert(indexToRepeat, sb.charAt(indexToRepeat));
        repCount--;
        }
    return sb.toString();
  }
/*
 * Entry point of the code.
 */
  public static void main(String[] args) {
    String filePath = "/usr/share/dict/words";;
    BadWordGenerator bwg = new BadWordGenerator();
    Scanner scanner = null;
    String word = null;
    try {
      scanner = new Scanner(new FileInputStream(filePath));
      while(scanner.hasNextLine()) {
      word = scanner.nextLine();
      String repLetters = bwg.repeatLetters(word);
      String caseChanged = bwg.changeCase(repLetters);
      String vowelsChanged = bwg.changeVowels(caseChanged);
      System.out.println(vowelsChanged);
      }
    } catch(IOException e) {
      System.err.println(e.toString());
      e.printStackTrace();
    } finally {
      if(scanner != null) {
        scanner.close();
            }
        }
    }
}
